name: Check manually maintained metadata about ontologies

on:
  pull_request:
    branches:
      - master
  schedule:
    # FYI: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html
    #
    #                   ,- month of the year
    # day of the month /
    #        hour |   /
    #    minute | |  / ,-- day of the week
    #         | | | | |
    - cron:  '* * * * 0'
    #                 `-- 0 = Sunday

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        ini-values: memory_limit=1G

    # Setup PHP environment (install dependencies etc.)
    - name: Install Composer dependencies
      run: cd scripts && composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Check
      run: scripts/bin/check-manually-maintained-metadata
