name: Continuous Integration

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        ini-values: memory_limit=1G
        tools: cs2pr

    # Validate composer.json
    - name: Validate Composer files
      run: cd scripts && composer validate --no-check-all --strict

    # Setup PHP environment (install dependencies etc.)
    - name: Install Composer dependencies
      run: cd scripts && composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    # Static code analyser
    - name: Static Code Analysis
      run: cd scripts && vendor/bin/phpstan analyse

    # Tests
    - name: Tests
      run: cd scripts && vendor/bin/phpunit

    # CSV linter
    - name: Lint index.csv
      uses: kcheriyath/csvlinter@V0.6.0
      with:
        file_list: "index.csv"
        find_pattern: "*.csv"
        find_path: "./"
        fail_on_error: "true"
